language: go

os:
  - linux
  - osx

go:
  - 1.10.x
  - 1.14.x

env:
  global:
    - PROJ="github.com/elastic/gosigar"

sudo: false

before_install:
  # Put project into proper GOPATH location (important for forks).
  - mkdir -p $HOME/gopath/src/${PROJ}
  - rsync -az ${TRAVIS_BUILD_DIR}/ $HOME/gopath/src/${PROJ}/
  - export TRAVIS_BUILD_DIR=$HOME/gopath/src/${PROJ}
  - cd $HOME/gopath/src/${PROJ}

install:
  - go get -v -t -d ./...

script:
  - gofmt -l . | read && echo "Code differs from gofmt's style. Run 'gofmt -w .'" 1>&2 && exit 1 || true
  - go vet
  - go build
  - go test -v ./...
  - for i in $(ls examples); do go build -o examples/$i/$i ./examples/$i; ./examples/$i/$i; done